import React from "react";
import { api } from "~/utils/api";
import { useUser } from "@clerk/nextjs";
import Head from "next/head";
const Cart: React.FC = () => {
  // const user = useUser();

  // const { data, isLoading } = api.posts.getAll.useQuery();

  // if (isLoading) return <div>Loading...</div>;

  // if (!data) return <div>Something went wrong...</div>;

  return (
    <div>
      <Head>
        <title>E-commerce : Cart</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Cart</h1>
    </div>
  );
};

export default Cart;
