import React from "react";
import { api } from "~/utils/api";
import { useUser } from "@clerk/nextjs";
import Head from "next/head";
const Landing: React.FC = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong...</div>;

  return (
    <div>
      <Head>
        <title>E-commerce : Landing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {data?.map((post) => (
          <div key={post.id}>{post.content}</div>
        ))}
      </div>
    </div>
  );
};

export default Landing;
