import { useRouter } from "next/router";

import Head from "next/head";
import { api } from "~/utils/api";

import { useUser } from "@clerk/nextjs";

import Navbar from "~/components/navbar/Navbar";
import Cart from "~/components/cart/Cart";
import Dashboard from "~/components/dashboard/Dashboard";
import Landing from "~/components/landing/Landing";

export default function Home() {
  const router = useRouter();

  const MainContent = () => {
    if (router.pathname === "/cart") {
      return <Cart />;
    } else if (router.pathname === "/dashboard") {
      return <Dashboard />;
    } else if (router.pathname === "/") {
      return <Landing />;
    } else {
      return (
        <>
          <h1>Content:</h1>
          {/* rest of your main content for the home page */}
        </>
      );
    }
  };

  return (
    <>
      {/* <Head>
        <title>E-commerce : Landing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Navbar />
      <main className="">
        <MainContent />
      </main>
    </>
  );
}
// runs on our device
