import React from "react";
import Head from "next/head";

const Dashboard: React.FC = () => {

  return (
    <div>
      <Head>
        <title>E-commerce : Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Dashboard</h1>
    </div>
  );
};

export default Dashboard;
